import { Scale, FileText, AlertTriangle, UserCheck } from 'lucide-react'

export function LegalDisclaimer() {
  return (
    <div className="bg-amber-50 dark:bg-slate-800 border border-amber-200 dark:border-slate-700 rounded-lg p-6 mb-8">
      <div className="flex gap-4">
        {/* Icon Column */}
        <div className="flex-shrink-0">
          <div className="w-14 h-14 bg-amber-600 dark:bg-slate-700 rounded-lg flex items-center justify-center">
            <Scale className="dark:text-blue-400 h-6 w-66 text-white" />
          </div>
        </div>
        
        {/* Content Column */}
        <div className="flex-1">
          <h3 className="text-lg font-semibold text-amber-900 dark:text-white mb-4">
            Important Legal Disclaimer
          </h3>
          
          <div className="space-y-4 text-sm">
            <div className="flex items-start gap-3">
              <FileText className="h-4 w-4 text-amber-600 dark:text-blue-400 mt-0.5 flex-shrink-0" />
              <div>
                <p className="font-medium text-amber-800 dark:text-gray-200 mb-1">
                  Templates Only:
                </p>
                <p className="text-amber-700 dark:text-gray-300">
                  The contracts generated by this website are templates for informational and educational purposes only.
                </p>
              </div>
            </div>

            <div className="flex items-start gap-3">
              <AlertTriangle className="h-4 w-4 text-amber-600 dark:text-blue-400 mt-0.5 flex-shrink-0" />
              <div>
                <p className="font-medium text-amber-800 dark:text-gray-200 mb-1">
                  Not Legal Advice:
                </p>
                <p className="text-amber-700 dark:text-gray-300">
                  This service does not provide legal advice, legal representation, or legal services of any kind.
                </p>
              </div>
            </div>

            <div className="flex items-start gap-3">
              <UserCheck className="h-4 w-4 text-amber-600 dark:text-blue-400 mt-0.5 flex-shrink-0" />
              <div>
                <p className="font-medium text-amber-800 dark:text-gray-200 mb-1">
                  Consult an Attorney:
                </p>
                <p className="text-amber-700 dark:text-gray-300">
                  You should consult with a qualified attorney in your jurisdiction before using any contract for legal purposes.
                </p>
              </div>
            </div>

            <div className="bg-amber-100 dark:bg-slate-700 rounded-lg p-4 mt-4">
              <p className="font-medium text-amber-800 dark:text-gray-200 mb-1">
                No Liability:
              </p>
              <p className="text-amber-700 dark:text-gray-300">
                FastContracts and its operators disclaim all liability for any legal issues, disputes, or damages that may arise from the use of these contract templates. Use at your own risk.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
